[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
PORT = { value = "8000" }

# Build configuration
[build.environment]
PYTHON_VERSION = "3.11"